using UnityEngine;

public class PlayerMov : MonoBehaviour
{
    public float speed = 5f;
    public Camera cam;

    void Update()
    {
        float move = Input.GetAxisRaw("Horizontal");

        float leftLimit =
            cam.transform.position.x
            - cam.orthographicSize * cam.aspect;

        Vector3 pos = transform.position;

        // ğŸ”¥ ì™¼ìª½ ê²½ê³„ì— ìˆê³ , ì™¼ìª½ìœ¼ë¡œ ê°€ë ¤ í•˜ë©´ ì´ë™ ì°¨ë‹¨
        if (pos.x <= leftLimit && move < 0)
        {
            move = 0;
        }

        // ì´ë™
        pos.x += move * speed * Time.deltaTime;
        transform.position = pos;
    }
}

